### ISSUE TITLE
Add the ability to change the wg interface name

### ISSUE THREAD

**Issue by LhuanDula** [shuricksumy/docker-wgdashboard#19]
Hi,

currently, the entrypoint.sh script (more specifically the set_envvars function) only allows the use of wg interfaces named wg[0-9].
It would be nice to extend the naming convention to any WG interface.
Like WG_[*]_POST_UP.

Cheers,

**Comment by shuricksumy** [comment]
> Hi,
> 
> currently, the entrypoint.sh script (more specifically the set_envvars function) only allows the use of wg interfaces named wg[0-9]. It would be nice to extend the naming convention to any WG interface. Like WG_[*]_POST_UP.
> 
> Cheers,

Hi, @LhuanDula 

I think it’s easy to implement it terms of bash script, but need to test this within wgdashboard. It also requires to rewrite starting interface script.

So just to clarify, what is interface names are you using? Currently it was implemented like wg0, wg1…wgN.

**Comment by LhuanDula** [comment]
That's good news. Currently, I'm naming my interfaces WG_[LOCATION]_[TYPEOFSERVICE].

I believe that naming all interfaces starting by wg/WG seems reasonnable.

**Comment by shuricksumy** [comment]
Ok, I will try to do that next week.

**Comment by shuricksumy** [comment]
@LhuanDula 
I created pull request.

Just to double check if this will cover your case.

1. No need to define scripts inside compose file
2. It will be automatically based on the next logic

- PreUp - put script into ./scripts/ folder with template name **<font style="color:orange">[interface_name]_pre_up.sh</font>**
- PostUp - put script into ./scripts/ folder with template name **<font style="color:orange">[interface_name]_post_up.sh</font>**
- PreDown - put script into ./scripts/ folder with template name **<font style="color:orange">[interface_name]_pre_down.sh</font>**
- PostDown - put script into ./scripts/ folder with template name **<font style="color:orange">[interface_name]_post_down.sh</font>**

**Comment by LhuanDula** [comment]
Hi @shuricksumy,
sorry for the long delay, I was out of town.

Works as advertised on my part.
Many thanks for the quick changes, this makes having nicely named interfaces easier.

Cheers,
