### ISSUE TITLE
Iptables-legacy support missing since v4.0.4-fix2 

### ISSUE THREAD

**Issue by LhuanDula** [shuricksumy/docker-wgdashboard#44]
Hi,

I noticed that since v4.0.4-fix2 I'm not able to use iptables-legacy anymore.
The binaries are missing from the docker image.

Some of my docker hosts still uses iptables-legacy instead of the nft-tables.
Would it be possible to add back support for iptables-legacy?

Cheers,

**Comment by shuricksumy** [comment]
It looks like I can create image based on debian with supporting legacy. I will do this and let you know. It will be separate tag for image.

**Comment by shuricksumy** [comment]
@LhuanDula 
Please check, I created the separate image
- docker pull ghcr.io/shuricksumy/docker-wgdashboard:debian-latest
- docker pull shuricksumy/wgdashboard:debian-latest

**Comment by LhuanDula** [comment]
Works as intended!
Thanks @shuricksumy
